# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-21 17:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_files', '0002_auto_20151121_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces_files.Folder'),
        ),
    ]
