# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import private_media.storages
import spaces_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_files', '0005_auto_20151123_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=private_media.storages.PrivateMediaStorage(), upload_to=spaces_files.models.file_upload_path),
        ),
    ]
