# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 14:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_files', '0006_auto_20160111_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces_files.Folder', verbose_name='parent folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='spaces_files.Folder', verbose_name='parent folder'),
        ),
    ]
