# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-22 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces_files', '0007_auto_20160223_1545'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='folder',
            managers=[
            ],
        ),
    ]
